server:
  address: "server:12345"
loop:
  amount: 500
  period: "150ms"
log:
  level: "INFO"
batch:
  maxAmount: 10
NOMBRE: "Santiago Lionel"
APELLIDO: "Lorca"
DOCUMENTO: 30904465
NACIMIENTO: "1999-03-17"
NUMERO: 7574
